package utils

func GetStatIDToNameMap() map[string]string {
	return map[string]string{
		"0":    "Games Played",
		"1":    "Goals",
		"2":    "Assists",
		"3":    "Points",
		"4":    "Plus/Minus",
		"5":    "Penalty Minutes",
		"6":    "Powerplay Goals",
		"7":    "Powerplay Assists",
		"8":    "Powerplay Points",
		"9":    "Shorthanded Goals",
		"10":   "Shorthanded Assists",
		"11":   "Game-Winning Goals",
		"12":   "Overtime Goals",
		"13":   "Empty Net Goals",
		"14":   "Shots on Goal",
		"15":   "Shooting Percentage",
		"16":   "Faceoff Wins",
		"17":   "Faceoff Losses",
		"18":   "Powerplay Opportunities",
		"19":   "Wins",
		"20":   "Time on Ice Per Game",
		"21":   "Games Started",
		"22":   "Goals Against",
		"23":   "Shootout Goals",
		"24":   "Shootout Attempts",
		"25":   "Saves",
		"26":   "Goals Saved Above Average",
		"27":   "Shutouts",
		"28":   "Save Percentage",
		"29":   "Goals Per Game",
		"30":   "Assists Per Game",
		"31":   "Hits",
		"32":   "Blocks",
		"33":   "Time on Ice",
		"34":   "Average Time on Ice",
		"1001": "Corsi For",
		"1002": "Corsi Against",
		"1003": "Fenwick For",
		"1004": "Fenwick Against",
		"1005": "Scoring Chances For",
		"1006": "Scoring Chances Against",
		"1007": "High-Danger Chances For",
		"1008": "High-Danger Chances Against",
		"1009": "High-Danger Conversion %",
		"1010": "Penalties Drawn",
		"1011": "Penalties Taken",
	}
}

func GetNHLTeamAbbreviations() map[string]string {
	return map[string]string{
		"ANA": "Anaheim Ducks",
		"BOS": "Boston Bruins",
		"BUF": "Buffalo Sabres",
		"CGY": "Calgary Flames",
		"CAR": "Carolina Hurricanes",
		"CHI": "Chicago Blackhawks",
		"COL": "Colorado Avalanche",
		"CBJ": "Columbus Blue Jackets",
		"DAL": "Dallas Stars",
		"DET": "Detroit Red Wings",
		"EDM": "Edmonton Oilers",
		"FLA": "Florida Panthers",
		"LAK": "Los Angeles Kings",
		"MIN": "Minnesota Wild",
		"MTL": "Montreal Canadiens",
		"NSH": "Nashville Predators",
		"NJD": "New Jersey Devils",
		"NYI": "New York Islanders",
		"NYR": "New York Rangers",
		"OTT": "Ottawa Senators",
		"PHI": "Philadelphia Flyers",
		"PIT": "Pittsburgh Penguins",
		"SJS": "San Jose Sharks",
		"SEA": "Seattle Kraken",
		"STL": "St. Louis Blues",
		"TBL": "Tampa Bay Lightning",
		"TOR": "Toronto Maple Leafs",
		"UTA": "Utah Hockey Club",
		"VAN": "Vancouver Canucks",
		"VGK": "Vegas Golden Knights",
		"WSH": "Washington Capitals",
		"WPG": "Winnipeg Jets",
	}
}
